In [11]:
import pandas as pd

df = pd.read_csv('wmt.csv')
df

  Line Item  2017Q1  2017Q2  2017Q3  2017Q4  2018Q1
0   Revenue  115904  120854  118179  130936  117542
1  Expenses   86544   89485   87484   97743   87688
2    Profit   29360   31369   30695   33193   29854

In [12]:
df.set_index('Line Item',inplace=True)

In [13]:
df.index

Index(['Revenue', 'Expenses', 'Profit'], dtype='object', name='Line Item')

In [15]:
df = df.T
df

           2017Q1  2017Q2  2017Q3  2017Q4  2018Q1
Line Item
Revenue    115904  120854  118179  130936  117542
Expenses    86544   89485   87484   97743   87688
Profit      29360   31369   30695   33193   29854

In [18]:
df.index = pd.PeriodIndex(df.index, freq='Q-JAN')
df

DateParseError: Unknown datetime string format, unable to parse: REVENUE